env:
    node: true
    es2021: true
    browser: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:@typescript-eslint/eslint-recommended
    - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
    project: "./tsconfig.json"
plugins:
    - "@typescript-eslint"
    - prettier
rules:
    "prettier/prettier": "error"
    "@typescript-eslint/no-floating-promises": "error"
